server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 5
        batch.size: 16384
        buffer.memory: 33554432

app:
  kafka:
    topic: words.processed
    partitions: 4
    replicas: 1
  hipsum:
    base-url: https://hipsum.co/api/