server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/betvictor
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: repository-app-group
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:latest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      concurrency: ${KAFKA_CONSUMER_CONCURRENCY:4}
      ack-mode: record

app:
  kafka:
    topic: words.processed
    dlt:
      topic: words.processed.DLT
      max-attempts: 3
